// <auto-generated />
using System;
using FISCA.Infraestructura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FISCA.Infraestructura.Migrations
{
    [DbContext(typeof(AplicacionDbContexto))]
    [Migration("20240521211819_Setup06")]
    partial class Setup06
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FISCA.Dominio.Entidades.Asignacion", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAsignatura")
                        .HasColumnType("int");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdHorario")
                        .HasColumnType("int");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.Property<int>("NumeroAsignacion")
                        .HasColumnType("int");

                    b.HasKey("IdAsignacion");

                    b.ToTable("asignaciones");

                    b.HasData(
                        new
                        {
                            IdAsignacion = 1,
                            Descripcion = "Waos",
                            Estado = "Activo",
                            IdAsignatura = 1,
                            IdDocente = 1,
                            IdGrupo = 1,
                            IdHorario = 1,
                            IdTurno = 1,
                            NumeroAsignacion = 1
                        });
                });

            modelBuilder.Entity("FISCA.Dominio.Entidades.Asignatura", b =>
                {
                    b.Property<int>("IdAsignatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignatura"));

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int");

                    b.Property<int>("IdCuatrimestre")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<string>("NombreAsignatura")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAsignatura");

                    b.ToTable("asignaturas");

                    b.HasData(
                        new
                        {
                            IdAsignatura = 1,
                            IdCarrera = 1,
                            IdCuatrimestre = 1,
                            IdGrupo = 1,
                            NombreAsignatura = "Analisis Matematico"
                        });
                });

            modelBuilder.Entity("FISCA.Dominio.Entidades.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrera"));

                    b.Property<string>("NombreCarrera")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCarrera");

                    b.ToTable("carreras");

                    b.HasData(
                        new
                        {
                            IdCarrera = 1,
                            NombreCarrera = "Waza"
                        });
                });

            modelBuilder.Entity("FISCA.Dominio.Entidades.Cuatrimestre", b =>
                {
                    b.Property<int>("IdCuatrimestre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuatrimestre"));

                    b.Property<string>("NombreCuatrimestre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCuatrimestre");

                    b.ToTable("cuatrimestres");

                    b.HasData(
                        new
                        {
                            IdCuatrimestre = 1,
                            NombreCuatrimestre = "Pruebita"
                        });
                });

            modelBuilder.Entity("FISCA.Dominio.Entidades.Docente", b =>
                {
                    b.Property<int>("IdDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocente"));

                    b.Property<string>("ApellidosDocente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CedulaDocente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CelularDocente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoDocente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionDocente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombresDocente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoDocente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDocente");

                    b.ToTable("docentes");

                    b.HasData(
                        new
                        {
                            IdDocente = 1,
                            ApellidosDocente = "Gimenez Garcilazo",
                            CedulaDocente = "72546978",
                            CelularDocente = "978456123",
                            CorreoDocente = "pedro@upla.edu.pe",
                            DireccionDocente = "Psje. Chifuentes",
                            Estado = 1,
                            Foto = "",
                            NombresDocente = "Pedro",
                            TelefonoDocente = "064526"
                        });
                });

            modelBuilder.Entity("FISCA.Dominio.Entidades.Inscripciones_Asignaturas", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<DateTime?>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAsignatura")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdInscripcion");

                    b.ToTable("inscripcionesAsignaturas");

                    b.HasData(
                        new
                        {
                            IdInscripcion = 1,
                            FechaInscripcion = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAsignatura = 1,
                            IdEstudiante = 1,
                            Observaciones = "JAJAJAJA"
                        },
                        new
                        {
                            IdInscripcion = 2,
                            FechaInscripcion = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAsignatura = 2,
                            IdEstudiante = 2,
                            Observaciones = "JEJEJEJE"
                        });
                });

            modelBuilder.Entity("FISCA.Dominio.Entidades.Material_Didactico", b =>
                {
                    b.Property<int>("IdMaterialDidactico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterialDidactico"));

                    b.Property<string>("Archivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoMaterial")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdNumeroAsignacion")
                        .HasColumnType("int");

                    b.HasKey("IdMaterialDidactico");

                    b.ToTable("materialDidacticos");

                    b.HasData(
                        new
                        {
                            IdMaterialDidactico = 1,
                            Archivo = "Hotel 1 star",
                            CodigoMaterial = 1,
                            Descripcion = "Hotel 01",
                            FechaSubida = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDocente = 1,
                            IdNumeroAsignacion = 1
                        },
                        new
                        {
                            IdMaterialDidactico = 2,
                            Archivo = "Hotel 2 star",
                            CodigoMaterial = 2,
                            Descripcion = "Hotel 02",
                            FechaSubida = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDocente = 2,
                            IdNumeroAsignacion = 2
                        });
                });

            modelBuilder.Entity("FISCA.Dominio.Entidades.Mensajes", b =>
                {
                    b.Property<int>("IdMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMensaje"));

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remitio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMensaje");

                    b.ToTable("mensajes");

                    b.HasData(
                        new
                        {
                            IdMensaje = 1,
                            Correo = "diego@gmail.com",
                            FechaEnvio = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mensaje = "Anuel AA",
                            Remitente = "Juan",
                            Remitio = "Pedro"
                        },
                        new
                        {
                            IdMensaje = 2,
                            Correo = "die@gmail.com",
                            FechaEnvio = new DateTime(2027, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mensaje = "Anuela AA",
                            Remitente = "Juana",
                            Remitio = "Pedra"
                        });
                });

            modelBuilder.Entity("FISCA.Dominio.Entidades.Niveles", b =>
                {
                    b.Property<int>("IdNivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNivel"));

                    b.Property<string>("NombreNivel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNivel");

                    b.ToTable("niveles");

                    b.HasData(
                        new
                        {
                            IdNivel = 1,
                            NombreNivel = "pollo"
                        },
                        new
                        {
                            IdNivel = 2,
                            NombreNivel = "Gumball"
                        });
                });

            modelBuilder.Entity("FISCA.Dominio.Entidades.Numeros_Asignaciones", b =>
                {
                    b.Property<int>("IdNumerosAsignaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNumerosAsignaciones"));

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.Property<int>("NumeroAsignado")
                        .HasColumnType("int");

                    b.HasKey("IdNumerosAsignaciones");

                    b.ToTable("numeros_Asignaciones");

                    b.HasData(
                        new
                        {
                            IdNumerosAsignaciones = 1,
                            IdDocente = 1,
                            NumeroAsignado = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
